language:php
php:7.1

before_script:
  -composer require "squizlabs/php_codesniffer=*"
  -composer install

script:
  -phpcs ./classes


notifications:
  email:
    on_success: never
    on_failure: always
